# Generated by Django 5.1.2 on 2025-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'verbose_name': 'Janr', 'verbose_name_plural': 'Janrlar'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='janrlar', to='main.categorys', verbose_name='Janri'),
        ),
    ]
