# Generated by Django 5.1.2 on 2025-03-03 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categorys_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanlangan kitob',
                'verbose_name_plural': 'Tanlangan kitoblar',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
