# Generated by Django 5.1.2 on 2025-03-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_featuredbooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedBooks',
            new_name='SelectedBooks',
        ),
    ]
