# Generated by Django 5.1.2 on 2025-03-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_featuredbooks_selectedbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.books')),
            ],
            options={
                'verbose_name': 'Sotilgan kitob',
                'verbose_name_plural': 'Sotilgan kitoblar',
            },
        ),
    ]
