# Generated by Django 5.1.2 on 2025-03-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sellingbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingbooks',
            name='count',
            field=models.PositiveIntegerField(default=2, verbose_name='soni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellingbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.books', verbose_name='kitob'),
        ),
        migrations.AlterField(
            model_name='sellingbooks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='sellingbooks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="o'zgartirilgan vaqti"),
        ),
    ]
