# Generated by Django 5.1.2 on 2025-03-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sellingbooks_count_alter_sellingbooks_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedbooks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbooks',
            name='count',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='soni'),
        ),
    ]
