# Generated by Django 5.1.2 on 2025-03-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_selectedbooks_updated_at_alter_sellingbooks_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedbooks',
            unique_together=set(),
        ),
    ]
