# Generated by Django 5.1.2 on 2025-03-05 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_selectedbooks_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Muallifi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Familya'),
        ),
        migrations.AlterField(
            model_name='selectedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.books', verbose_name='Kitob'),
        ),
        migrations.AlterField(
            model_name='selectedbooks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='selectedbooks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='selectedbooks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='sellingbooks',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='sotilgan soni'),
        ),
        migrations.CreateModel(
            name='OfferBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='chegirma narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="o'zgartirilgan vaqti")),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.books', verbose_name='kitob')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
            },
        ),
    ]
